buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        implementation 'com.github.centic9:poi-on-android:4.1.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
} 